# Generated by Django 6.1.1 on 2026-09-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_connection_status_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['sender', 'status'], name='chat_intere_sender__2821dd_idx'),
        ),
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['receiver', 'status'], name='chat_intere_receive_9cce2a_idx'),
        ),
    ]
