# Generated by Django 6.1.1 on 2026-09-22 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100)),
                ('verification_type', models.CharField(choices=[('GOVT_ID', 'Government ID / KYC'), ('AADHAAR_DIGILOCKER', 'Aadhaar via DigiLocker'), ('PASSPORT', 'Passport Verification')], default='GOVT_ID', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
                'db_table': 'identity_verifications',
            },
        ),
    ]
