# Generated by Django 6.1.1 on 2026-09-22 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identityverification',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='provider_reference',
        ),
        migrations.RemoveField(
            model_name='identityverification',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='identityverification',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='verification_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar Card Document'), ('GOVT_ID', 'Government Issued ID'), ('PASSPORT', 'Passport')], default='AADHAAR', max_length=30),
        ),
    ]
