# Generated by Django 6.1.1 on 2026-09-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_remove_identityverification_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='verification_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENCE', 'Driving Licence'), ('VOTER_ID', 'Voter ID')], default='AADHAAR', max_length=30),
        ),
    ]
