# Generated by Django 6.1.1 on 2026-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_identityverification_verification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
