# Generated by Django 6.1.1 on 2026-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_identityverification_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
