# Generated by Django 5.2.17 on 2026-09-21 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height_feet_inches', models.CharField(default='5\' 8"', max_length=20)),
                ('height_cm', models.IntegerField(default=172)),
                ('weight_kg', models.IntegerField(blank=True, default=68, null=True)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorce', 'Awaiting Divorce')], default='Never Married', max_length=30)),
                ('religion', models.CharField(default='Hindu', max_length=50)),
                ('caste', models.CharField(default='Brahmin', max_length=50)),
                ('sub_caste', models.CharField(blank=True, default='', max_length=50)),
                ('mother_tongue', models.CharField(default='Hindi', max_length=50)),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('avatar_file', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(default='Software Engineer / Corporate Executive', max_length=150)),
                ('employed_in', models.CharField(default='Private Sector', max_length=100)),
                ('company_name', models.CharField(default='Global Technology Firm', max_length=150)),
                ('annual_income', models.CharField(default='₹20 - 25 Lakhs P.A.', max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_details', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=23)),
                ('max_age', models.IntegerField(default=32)),
                ('min_height', models.CharField(default='5\' 2"', max_length=20)),
                ('max_height', models.CharField(default='6\' 2"', max_length=20)),
                ('marital_status', models.CharField(default='Never Married', max_length=50)),
                ('religion', models.CharField(default='Hindu', max_length=50)),
                ('caste', models.CharField(default='Brahmin / Open to All', max_length=100)),
                ('education_level', models.CharField(default='Graduate / Post Graduate', max_length=100)),
                ('occupation', models.CharField(default='Corporate / Government / Tech', max_length=100)),
                ('min_income', models.CharField(default='₹15 Lakhs+ P.A.', max_length=100)),
                ('location', models.CharField(default='India / Major Metro Cities', max_length=150)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(default='Vegetarian', max_length=50)),
                ('drinking', models.CharField(default='Never', max_length=50)),
                ('smoking', models.CharField(default='Never', max_length=50)),
                ('hobbies', models.TextField(default='Reading, Music, Travel, Yoga')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_details', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_type', models.CharField(default='Nuclear Family', max_length=50)),
                ('family_values', models.CharField(default='Moderate Traditional', max_length=50)),
                ('father_occupation', models.CharField(default='Retired Senior Officer', max_length=150)),
                ('mother_occupation', models.CharField(default='Homemaker', max_length=150)),
                ('brothers_count', models.IntegerField(default=1)),
                ('sisters_count', models.IntegerField(default=0)),
                ('native_place', models.CharField(default='Indore, Madhya Pradesh', max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='B.Tech / Post Graduate', max_length=150)),
                ('field_of_study', models.CharField(default='Computer Science & Management', max_length=150)),
                ('institution', models.CharField(default='IIT / Reputed University', max_length=200)),
                ('education_level', models.CharField(default='Master / Post Graduate', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to='profiles.profile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('marriage_date', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'target_profile')},
            },
        ),
    ]
