# Generated by Django 6.1.1 on 2026-09-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_educationdetails_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetails',
            name='additional_degree',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='passing_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='about_family',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='family_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='married_brothers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='married_sisters_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='lifestyledetails',
            name='exercise',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lifestyledetails',
            name='interests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lifestyledetails',
            name='pets',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreferences',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreferences',
            name='drinking',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreferences',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerpreferences',
            name='smoking',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreferences',
            name='sub_caste',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='professionaldetails',
            name='experience_years',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='professionaldetails',
            name='work_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='complexion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='gothram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_known',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='physical_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(default='All Members', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height_feet_inches',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Awaiting Divorce', 'Awaiting Divorce')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
