# Generated by Django 6.1.1 on 2026-09-23 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shortlist',
            constraint=models.UniqueConstraint(fields=('user', 'target_profile'), name='unique_user_shortlist'),
        ),
    ]
