# Generated by Django 6.1.1 on 2026-09-24 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_shortlist_unique_user_shortlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAKE_PROFILE', 'Fake / Inappropriate Profile'), ('HARASSMENT', 'Harassment / Abuse'), ('INAPPROPRIATE_CONTENT', 'Inappropriate Content / Photos'), ('SPAM', 'Spam / Commercial Messages'), ('OTHER', 'Other Safety Issue')], max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved / Action Taken'), ('DISMISSED', 'Dismissed / Invalid')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='profiles_us_status_d1b836_idx'), models.Index(fields=['reported_user', 'status'], name='profiles_us_reporte_a82b9f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reporter', models.F('reported_user')), _negated=True), name='prevent_self_report')],
            },
        ),
    ]
